import { CSSProperties } from 'react';
import { IconType } from '../Icon';
export interface DropdownProps {
    message?: string;
    itemStyle?: CSSProperties;
    valueStyle?: CSSProperties;
    listStyle?: CSSProperties;
    onOpen?: () => void;
    onClose?: () => void;
    value: Array<string | number>;
    valueTemplate?: (value?: (string | number)[]) => React.ReactNode;
    dataKey?: string;
    dataLabel?: string;
    options: Array<any>;
    itemTemplate?: (option: any, isActive: boolean, isSelected: boolean) => React.ReactNode;
    align?: 'left' | 'right';
    multiSelect?: boolean;
    search?: boolean;
    disabled?: boolean;
    valueIcon?: string;
    emptyMessage?: string;
    placeholder?: string;
    isChanged?: boolean;
    isMultiple?: boolean;
    onChange?: (v: (string | number)[]) => void;
    maxOptionsShown?: number;
    style?: CSSProperties;
    className?: string;
    widthExpand?: boolean;
    searchFields?: string[];
    minSelected?: number;
    dropIcon?: IconType;
}
export declare const Dropdown: import("react").ForwardRefExoticComponent<DropdownProps & import("react").RefAttributes<HTMLDivElement>>;
