import type { Meta, StoryObj } from '@storybook/react';
import { Dropdown } from '.';
declare const meta: Meta<typeof Dropdown>;
export default meta;
type Story = StoryObj<typeof Dropdown>;
export declare const Icons: Story;
export declare const Basic: Story;
export declare const Search: Story;
export declare const Multiple: Story;
export declare const CustomTemplates: Story;
