import type { Meta, StoryObj } from '@storybook/react';
import { InputColor } from './InputColor';
declare const meta: Meta<typeof InputColor>;
export default meta;
type Story = StoryObj<typeof InputColor>;
export declare const HEX: Story;
export declare const HEXA: Story;
export declare const Uint8: Story;
export declare const Uint8A: Story;
export declare const Float: Story;
export declare const Uint16: Story;
